### ISSUE TITLE
Allow to specify priority also for a periodic job

### ISSUE THREAD

**Issue by medihack** [procrastinate-org/procrastinate#1072]
In PR #1070, we added a priority feature for normal jobs. The priority for periodic jobs is always 0. In the end, we would also like to let the user specify a priority for periodic jobs.

**Comment by ewjoachim** [comment]
I think it's kinda linked to the idea of setting a default priority for a task when defining the task (`@app.task(priority=5)`). I think it would make sense to do both in the same ticket (well, if we do the `@app.task(priority=5)`, we'll somehow need to make it work for periodic tasks)
