### ISSUE TITLE
Wrong documentation about verbose option

### ISSUE THREAD

**Issue by medihack** [procrastinate-org/procrastinate#1080]
The [documentation](https://procrastinate.readthedocs.io/en/stable/howto/basics/command_line.html) says that `PROCRASTINATE_VERBOSE` env variable can be set to change the verbosity of the worker. It is even set in [some](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/tests/acceptance/conftest.py#L18) [tests](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/tests/integration/test_cli.py#L36). On the other hand the CLI just uses [`VERBOSE`](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/procrastinate/cli.py#L185-L186) env var.  Or is the `PROCRASTINATE_` prefix somehow added automagically?

The documentation also says that the verbosity is controlled by using `v` multiple times and that there are 3 levels. But there are actually four levels and those are controlled by an integer.

**Comment by medihack** [comment]
Just found out that it just works a bit differently in the Django command. The normal `procrastinate` command supports the multiple `v` option.

**Comment by ewjoachim** [comment]
Yep, the `PROCRASTINATE_` prefix is [added automatically](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/procrastinate/cli.py#L155)

It used to be a feature from click but we had to stop using click due to async issues so we had to redevelop this behaviour on our side.

Regarding the `-v` behaviour, is there a place in the docs where this should be explicited ?

**Comment by medihack** [comment]
> Yep, the `PROCRASTINATE_` prefix is [added automatically](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/procrastinate/cli.py#L155)

Thanks, good to know.

> 
> It used to be a feature from click but we had to stop using click due to async issues so we had to redevelop this behaviour on our side.
> 
> Regarding the `-v` behaviour, is there a place in the docs where this should be explicited ?

There seems to be some differences between the basic `procrastinate` command and the Django alternative `./manage.py procrastinate.`

The basic command tells me in the help info about `verbose`:
```
-v, --verbose  Use multiple times to increase verbosity (env: PROCRASTINATE_VERBOSE: set to desired verbosity level) (default: 0)
```

The Django command on the other side prints out this in the help info:
```
-v {0,1,2,3}, --verbosity {0,1,2,3} Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
```

The Django command does not accept something like `-vv`.

The documentation also states that there are [3 different log levels](https://procrastinate.readthedocs.io/en/stable/howto/basics/command_line.html#logging) for verbose. But the above Django help info says that there are 4 log levels. And from looking at the code there are indeed [only two](https://github.com/procrastinate-org/procrastinate/blob/6c3e58248063c3c576ac37f054ba3055a3e819f8/procrastinate/cli.py#L27) levels. So it's a bit confusing 😉.

**Comment by ewjoachim** [comment]
Hm, true that, I think at some point we switched from default to `warning` to defaulting to `info`.

(I wonder if we should revisit this choice, but nobody complained. If that's really something people want to change, they can make their own executable that uses whatever value they want.)

And yes, Django manages its own `-v` in management commands. Could be worth piggy-backing on that (https://reinout.vanrees.org/weblog/2017/03/08/logging-verbosity-managment-commands.html) though we'll still have level mismatch.

Shouldn't be hard to explain wherever relevant in the doc.
