### ISSUE TITLE
Allow to set a cache option when polling for an abortion request

### ISSUE THREAD

**Issue by medihack** [procrastinate-org/procrastinate#1083]
It might be easier for users if we implemented say `def should_abort(cache=10)` that would cache the answer for 10 seconds. This way, one may call the method as often as they wish. The default time could be a worker param.

_Originally posted by @ewjoachim in https://github.com/procrastinate-org/procrastinate/pull/1081#discussion_r1651403431_

**Comment by ewjoachim** [comment]
Not relevant anymore now that we use listen/notify for abortions
