### ISSUE TITLE
Apply migrations using plain python

### ISSUE THREAD

**Issue by tomas-rojo** [procrastinate-org/procrastinate#1115]
Im trying to run migrations without using the CLI options.

I currently have this little piece of code:

```python
from procrastinate import App, PsycopgConnector


app = App(
    connector=PsycopgConnector(
        kwargs={
            "host": "localhost",
            "user": "postgres",
            "password": "password",
            "port": "5432"
        }
    )
)


with app.open():
    app.schema_manager.apply_schema()
```

But the error is quite confusing as I'm already using the context manager:

```
raise exceptions.AppNotOpen
procrastinate.exceptions.AppNotOpen: 
    App was not open. Procrastinate App needs to be opened using:

    - ``app.open()``,
    - ``await app.open_async()``,
    - ``with app.open():``,
    - ``async with app.open_async():``.
```

Can anyone please give me a hint?

**Comment by onlyann** [comment]
It looks like you uncovered a bug.

In the meantime, I think it should work if you use the ˋSyncPsycopgConnector` in the app's constructor.

**Comment by ewjoachim** [comment]
Hm, this is due to the SchemaManager using `async_to_sync` rather than `connector.get_sync_connector()` I think.
