### ISSUE TITLE
Django database errors not properly wrapped

### ISSUE THREAD

**Issue by katlyn** [procrastinate-org/procrastinate#1141]
When using procrastinate within a Django application, it appears that database errors from Django are not wrapped correctly in all cases, particularly `IntegrityError`s raised from `queueing_lock`. I believe the fix should be along the lines updating [/procrastinate/contrib/django/djago_connector.py#44](https://github.com/procrastinate-org/procrastinate/blob/73ba60adc4d636b3e01ebfd4425699ebbd4b0c26/procrastinate/contrib/django/django_connector.py#L44) to be similar to the following.
```python
try:
    yeild
except django.db.IntegrityError as exc:
    raise exceptions.UniqueViolation(*exc.args)
```
Unfortunately, as far as I can tell there's not a reliable way to extract `constraint_name` or other information, and I don't have the bandwidth to try to attempt to test and implement a full solution at this point in time.

## Steps to reproduce:
1. Set up procrastinate with a Django project.
2. Create a task with `queueing_lock` set.
3. Attempt to queue multiple jobs at a time.
4. Django's `IntegrityError` is raised instead of `AlreadyEnqueued`.

## Workaround
Use `except IntegrityError` instead of `AlreadyEnqueued`.

**Comment by paulzakin** [comment]
Yup, we get that as well. @ewjoachim is there a way for it to fail gracefully without throwing an exception?

**Comment by ewjoachim** [comment]
Oof, it's much worse than I thought, sorry.

We should fix it, I don't think there's a user workaround.

**Comment by paulzakin** [comment]
No worries - it's not a big deal operationally for us!

**Comment by davecoates** [comment]
I don't think you can extract the constraint name directly from the `IntegrityError`, but could do something like

```
with wrap():
    try:
        yield
    except IntegrityError as exc:
        constraint_name = None
        if QUEUEING_LOCK_CONSTRAINT in str(exc):
            constraint_name = QUEUEING_LOCK_CONSTRAINT
        raise exceptions.UniqueViolation(*exc.args, constraint_name=constraint_name)
```

which seems to work

**Comment by ewjoachim** [comment]
> I don't think you can extract the constraint name directly from the IntegrityError

@davecoates yes we can: django wraps the exception (pseudocode):

```python
try:
     psycopg.stuff()
except psycopg.Exception as exc:
    raise DjangoIntegrityError from exc
```
Which means we get the original exception in `__cause__`

```python
try:
    django.cursor.stuff()
except DjangoIntegrityError as exc:
    assert isinstance(DjangoIntegrityError.__cause__, DjangoIntegrityError)
```
so we can do `exc.__cause__.diag.constraint_name`

**Comment by davecoates** [comment]
Ahh right - so could just do this then?

```
with wrap():
    try:
        yield
    except DjangoIntegrityError as exc:
        # raise the original UniqueViolation
        raise exc.__cause__
```

**Comment by ewjoachim** [comment]
> Ahh right - so could just do this then?

[That's what we did precisley](https://github.com/procrastinate-org/procrastinate/pull/1162/files#diff-60d1fd97f0e60e4efb84e72f55f0ffab3c3a51aa8e9e400fa7f0d7c402244fe5R44-R52)

Also, https://github.com/procrastinate-org/procrastinate/releases/tag/2.13.1 is released with the fix.

**Comment by davecoates** [comment]
Brilliant - thanks for the quick release
