### ISSUE TITLE
Include cancelled aborted tasks in remove_old_jobs

### ISSUE THREAD

**Issue by katlyn** [procrastinate-org/procrastinate#1145]
Currently, the builtin `remove_old_jobs` task only removes jobs that are succeeded or (optionally) failed. This can lead to cancelled and aborted tasks piling up in the database.

https://github.com/procrastinate-org/procrastinate/blob/77bf6452856ce735572ec383718a2782cee9a8f0/procrastinate/manager.py#L198-L203

Ideally, there would be an additional parameter available to remove those types of jobs as well.

**Comment by medihack** [comment]
Yes, that sounds reasonable. We could have an `include_aborted` and `include_cancelled`. Also, the docstring seems to be wrong of [`delete_old_jobs.include_error`](https://github.com/procrastinate-org/procrastinate/blob/77bf6452856ce735572ec383718a2782cee9a8f0/procrastinate/manager.py#L195) (it's the other way around). Would you be interested in providing a PR? ☺️
