### ISSUE TITLE
Decide if we need two separate polling options for checking jobs and abortion requests

### ISSUE THREAD

**Issue by medihack** [procrastinate-org/procrastinate#1184]
_Originally posted by @ewjoachim in https://github.com/procrastinate-org/procrastinate/pull/1172#discussion_r1739744311_

**Comment by onlyann** [comment]
@medihack You might want to add to the description of this issue it is discussing 2 separate timeout polling intervals between checking for new jobs and checking for aborted jobs

**Comment by medihack** [comment]
Fixed by #1192
