### ISSUE TITLE
Retry Failed Job

### ISSUE THREAD

**Issue by mogol** [procrastinate-org/procrastinate#1195]
Hello!

What's the right way to retry failed jobs?

1) the existing `retry`  function throws an error because the job is not in a "doing" state
2) I tried "manual" approach with
```
with app.open():
    failed_jobs = app.job_manager.list_jobs(status='failed')
    for job in failed_jobs:
        app.job_manager.defer_job(job)
```

However, it’s not clear how to safely delete those failed jobs. For example, it seems dangerous to use delete_old_jobs because there might be new jobs that have failed and are yet to be retried.

Thanks

**Comment by medihack** [comment]
Hm, the [retry mechanism](https://procrastinate.readthedocs.io/en/stable/howto/advanced/retry.html) is rather intended to repeat a job that raised an error. `failed` is a final state (like `succeeded`, `cancelled` and `aborted`). Can't you decorate your task with something like `@app.task(retry=5)`? You can even [implement your own retry strategy](https://procrastinate.readthedocs.io/en/stable/howto/advanced/retry.html#implementing-your-own-strategy) for very advanced cases.

**Comment by mogol** [comment]
Yea, but it can still fail after all that. Right?

**Comment by medihack** [comment]
You can retry indefinitely (`@app.task(retry=True)`), or however you like it with a custom strategy. When using a custom strategy you inherit from `BaseRetryStrategy` and every time your job "fails" `get_retry_decision` is called, and you decide if you want to retry or not (e.g. based on the raised error).

**Comment by mogol** [comment]
So basically, if the work has to be done, the idiomatic way is to "infinitely" retry and keep it in doing state. 
Got it. Thanks for the quick reply!
