### ISSUE TITLE
Minor regression in types

### ISSUE THREAD

**Issue by paulzakin** [procrastinate-org/procrastinate#1201]
Hello! 

Noticed a regression(?) in typing on strict mode (with pyright) when you use the newest version of the library. I just ignored it via pyright so not urgent at all, but thought I should bring it up!

Example: 

```py
context: procrastinate.JobContext = args[0]
task = context.task 
```

pyright thinks task: Task[..., Unknown, ...] | None is the type of task. The Unknown seems to be the problem here.

**Comment by ewjoachim** [comment]
Hm, probably a consequence of https://github.com/procrastinate-org/procrastinate/pull/1196 then...

**Comment by paulzakin** [comment]
Not a biggie for us - and most of the new(?) types past - just a heads up

**Comment by ewjoachim** [comment]
I think we should do the quick fix now and work on the better fix (I've started work on that but it's long and complicated and I'm running a but behind on open source work).

Would you be interested in providing a PR for the quick fix ? (or... for the better one :D but you don't have to)

**Comment by ewjoachim** [comment]
Don't feel sad, it's positively *awesome* that you were able to make a fix here, alongside with your other typing fix a few weeks ago :) Even if you end up only contributing small PRs occasionally, you're doing it, which is highly appreciated and puts you in the 1st percentile of the most active Procrastinate users :)

:clap:
