### ISSUE TITLE
Increasing worker concurrency increases number of `fetch_job` queries to procrstatinate database tables

### ISSUE THREAD

**Issue by ashleyheath** [procrastinate-org/procrastinate#1209]
(mostly looking for a sanity check on this before I roll up my sleeves)

`run` in `worker.py` starts a `single_worker()` once for as many instances as the `concurrency` setting specifies. This means that each `NOTIFY` from postgres that a job is available causes `n` coroutines to wake up and check `fetch_job` (near) simultaneously. This means that the number of calls to `fetch_job` scales at `number_of_workers x concurrency` rather than `number_of_workers`.

Assuming this is an unintended side effect of the implementation, would a PR to change this so that `fetch_job` is only called once per `NOTIFY` be accepted?

**Comment by medihack** [comment]
Hi @ashleyheath. We completely refactored the worker for the upcoming v3 release (done mainly by @onlyann). Would you mind looking [at the new implementation of the worker](https://github.com/procrastinate-org/procrastinate/blob/v3/procrastinate/worker.py). Do you think it is already solved there?

**Comment by ashleyheath** [comment]
Hi @medihack, I've had a quick look at the refactor and it looks likely that it does solve the problem (though perhaps @onlyann can provide an opinion). Is there a timeline planned for the v3 release?

**Comment by ewjoachim** [comment]
I agree with everything @onlyann and @medihack have said.

I'll add that we have a [v3 milestone](https://github.com/procrastinate-org/procrastinate/milestone/2) that is getting completed and I plan to work on #1189 on the week-end.

**Comment by ewjoachim** [comment]
Closed in v3
