### ISSUE TITLE
DeprecationWarning with Python 3.8

### ISSUE THREAD

**Issue by elemoine** [procrastinate-org/procrastinate#126]
While running the tests on Python 3.8 we get a `DeprecationWarning`:

```
.../procrastinate/lib/python3.8/site-packages/aiopg/connection.py:90: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal
 in Python 3.10.
```

We get this warning several times.

**Comment by elemoine** [comment]
Although I am afraid we can't do much about it, the problem being in aiopg (`aiopg/connection.py:90`) and asyncio itself (`asyncio/queues.py:48`).

**Comment by ewjoachim** [comment]
Maybe we could ping them, if they haven’t solved it yet

**Comment by ewjoachim** [comment]
I believe #178 closed this. Can you confirm @elemoine ? Or @k4nar ? (reopen if not)

**Comment by k4nar** [comment]
No it didn't close this. This needs to be fixed in aiopg.

**Comment by ewjoachim** [comment]
I believe aiopg fixed the issue. I'm not seeing the warning anymore.
