### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by elemoine** [procrastinate-org/procrastinate#375]
It may be good thing to follow https://tools.ietf.org/id/draft-knodel-terminology-00.html and change the name of our "master" branch to "main".

**Comment by ewjoachim** [comment]
It's an interesting proposal. There is merit to changing but also merit to keeping master for a little longer (e.g. to avoid confusing beginners). Let's discuss it together :)

**Comment by ewjoachim** [comment]
We discussed it. For what I've seen so far, in the context of git, the push to change from master to main was mostly from allies, and while I may have missed important testimonies, I'm still struggling to find what underrepresented folks think of it.

While I'd really like this project to be inclusive, we have to think about the multiple dimensions of inclusivity, including making things easy for newcomers. I'll be glad to change in a few months time when this become commonplace and everyone knows how to switch between working on projects using master vs main, but as for now, I'd rather we keep master for a little while. Let's re-explore this in 6 months time ? In the meantime, if any underrepresented folks interacting with the project would be more comfortable with the change, just say the word and we'll do it right away, no fuss.

**Comment by ewjoachim** [comment]
We're a year later, main branches are definitely more commonplace now. I think it's the right moment to do the change !
