### ISSUE TITLE
arguments for periodic tasks

### ISSUE THREAD

**Issue by philipp-leanix** [procrastinate-org/procrastinate#436]
I want to add multiple periodic tasks that have different input arguments, which is currently not possible as far as I can tell.

For example:

```python

def foo(timestamp, a, b):
  return a + b

app.periodic(foo, cron="*/5 * * * *", kwargs={"a": 1, "b": 1))

app.periodic(foo, cron="*/1 * * * *", kwargs={"a": 2, "b": 2))
```
At the moment I use apscheduler to handle cronjobs that need arguments.

Are there plans to add support for this?

**Comment by ewjoachim** [comment]
Hey :)

Sorry for the late answer. You're right, we could make it available. Until then, the easiest way is probably to make 2 different function tasks which call foo.

**Comment by ewjoachim** [comment]
Notes for implementing this: I think it will be almost entirely in `periodic.py` and will involve adding a `kwargs` parameter to `PeriodicTask`.

**Comment by ewjoachim** [comment]
@elemoine I believe this issue was assigned and some work has started, do you confirm?
