### ISSUE TITLE
Integration with SQLAlchemy

### ISSUE THREAD

**Issue by mjpieters** [procrastinate-org/procrastinate#445]
I'm  looking to integrate Procrastinate with an existing Flask project that uses SQLAlchemy 1.4. While I don't mind creating an additional PostgreSQL connection to defer jobs, it would be better for resource use if there was an option to reuse an existing SQLAlchemy session (or engine).

The advantage is then that the Proscratinate integration would use the same existing connection pool, rather than doubling up the number of connections per thread.

For workers, the existing connection options suffice (although SQLAlchemy 1.4 has [asyncio support options](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#using-multiple-asyncio-event-loops) too these days).

**Comment by mjpieters** [comment]
Noting this here as an alternative path: I am also pondering just patching up `procratistane.utils.sync_await()` to use my [Flask asyncio integration](https://stackoverflow.com/a/58616001/100297), which runs the asyncio loop in a dedicated thread but requires that `asyncio.run_coroutine_threadsafe()` is used, after which the sync call will have to wait for a Future to resolve.

**Comment by elemoine** [comment]
Thanks for opening this issue @mjpieters!

I think having an `SQLAlchemyConnector` would make sense.

```py
from procrastinate import App, SQLAlchemyConnector
from sqlalchemy import create_engine

engine = create_engine('postgresql://scott:tiger@localhost:5432/mydatabase')

app = App(connector=SQLAlchemyConnector())
app.open(pool=engine.pool):
```

I guess the `SQLAlchemyConnector` would create its own SQLAlchemy engine, using the user-defined pool passed to the `open` function. I am just wondering if an SQLAlchemy pool can be shared across multiple engines…

An alternative is to provide the `SQLAlchemyConnector` with an engine:

```py
from procrastinate import App, SQLAlchemyConnector
from sqlalchemy import create_engine

engine = create_engine('postgresql://scott:tiger@localhost:5432/mydatabase')

app = App(connector=SQLAlchemyConnector(engine=engine))
app.open():
```

That would kinda break the fact that `app.open` can be called with a pool.

**Comment by ewjoachim** [comment]
If we do that, then we could also make it possible to use Django the same way.

**Comment by elemoine** [comment]
@mjpieters I just created #453 for exactly this. It would be great if you can have a look at my code, and test the `SQLAlchemyPsycopg2Connector` in your application.
