### ISSUE TITLE
Exceptions swallowed in the listener and periodic_deferrer

### ISSUE THREAD

**Issue by kriscode1** [procrastinate-org/procrastinate#493]
When the database connection drops, an exception gets raised in the listener and periodic_deferrer tasks, but they are logged and not re-raised here: https://github.com/procrastinate-org/procrastinate/blob/master/procrastinate/utils.py#L249

This is an issue because I'd like the workers to crash and restart if these two tasks need reset. Else the periodic tasks won't be running. 

Proposal: re-raise the exception and then wait on these two tasks in the [worker gather](https://github.com/procrastinate-org/procrastinate/blob/master/procrastinate/worker.py#L123-L128) too

**Comment by ewjoachim** [comment]
This looks like a concerning bug, I'll try to have a look. Thanks a lot for the technical analysis. Do you have a precise reproduction scenario ? (Otherwise I'll fiddle around with what you sibmitted already)

**Comment by ewjoachim** [comment]
Ok, I think I have it.
I'm wondering what would be the best way to fix the issue ?
- To crash the worker if those coroutines fail ?
- To have these coroutine autorestart in `task_context` ?
- To have the underlying functions (listener & periodic deferrer) survive a crash and loop ?

**Comment by ewjoachim** [comment]
Hm, should we count on whoever launches this process to relaunch it when we fail or should this program be resilient to intermittent DB failures ?

For the sake of simplicity, I think I'll go with the 1st solution here.

**Comment by kriscode1** [comment]
My setup for recreating this is having multiple workers running and then I manually restart the database. https://github.com/procrastinate-org/procrastinate/pull/494 has the workers gracefully stopping so the first strategy is great. One benefit to exiting instead of auto-restarting failed tasks is that users can decide what kind of backoff/retry strategy they want to use if any, with whatever tooling they like.
