### ISSUE TITLE
Improve doc based on feedback

### ISSUE THREAD

**Issue by ewjoachim** [procrastinate-org/procrastinate#546]
Looks like Procrastinate was featured on the orange website.
Let's browse the answers and see if there is interesting feedback to gather:
- Things we can do better
- Things we could explain better in the docs

Ping @noodlesuk: if you're the OP from HN, thanks :)

**Comment by ewjoachim** [comment]
I believe we could at least take a look at the alternative libs mentionned and add them to our list in the discussion page.

**Comment by kbakk** [comment]
Link to discussion: https://news.ycombinator.com/item?id=30126152
