### ISSUE TITLE
Working example with locks

### ISSUE THREAD

**Issue by matthewcummings** [procrastinate-org/procrastinate#568]
Hi, logging this as an issue, please update it as you deem appropriate. First of all, I love this library, thank you for building and supporting it. 

I have a fairly simple use case where I have a containerized and distributed service (running in a cluster) and I need to guarantee that th containers run a specific init command sequentially when they start up. I could use Redis or some other database but I already have Postgres in place and it feels wasteful and overly complicated to add something like Redis just for this use case. And so here I am.

However, I couldn't find a good example of how to use locks in the your doc/repo. I might just be missing it, but it would be great if you could point me to any examples that you have. My service is running Flask fwiw and I'm looking to add this lock code in my main app file. Thank you.

**Comment by ewjoachim** [comment]
Can you tell me a few more words on what you're trying to achieve ? An example maybe ? I think my answer will be more relevant if I'm sure I have understood your issue correctly :)

**Comment by matthewcummings** [comment]
Thanks for the quick response!

Yes, I have a service which runs multiple replicas. I like keeping my database schemas up to date so I set the service to run a migration at startup. The problem is that this happens concurrently i.e. N times when I am running N pods/containers.

I want a distributed lock that prevents the containers from running the migration at the same time. I understand that this will slow down the startup a bit but that's OK. So the way it should work is:
1) The containers start up.
2) One of them "wins" the race and creates a lock using `procrastination`. It then runs the migration.
3) Ideally, the lock will expire to handle the case where the migrating container hangs, crashes, etc and fails to release the lock.
4) The other containers block until, one by one, they can each acquire the lock, run the migration and continue. The subsequent migrations should be quick as they're effectively no-ops.

I have other plans to run a one-off job as pre-deployment step but because of other factors and my time constraints, I can't do that now. `procrastination` seems like the perfect fit for my use case for the time being, especially because I can just wire it up to my existing Postgres database.

**Comment by ewjoachim** [comment]
There's an ambiguity in your message whether you imply that the service you intend to run on your containers is the procrastinate worker process or an unrelated process for which procrastinate would solely be used for the startup phase. I'm going to assume the 2nd one but feel free to correct.

There are multiple ways in which the current procrastinate is not doing exactly what you plan:

- the procrastinate worker process is a `while True` loop, it's not supposed to stop, so you'll have to implement a clever way to have the procrastinate process finish and launch your own server. There is a one-shot mode in the worker options but it's not exactly what you're suggesting: it's executing tasks up until no task is executable and then exit with code 0.

- the only way to ensure that each of your n workers do something is to create n tasks, each one in its own dedicated queue, and then to have each worker listen to one of those n queues. But if you do that, I'm not 100% sure that a worker will wait for a task if this that has a lock and another task has the same lock and isn't finished yet IF that second task is in a queue that the first task doesn't listen to. That should be something to check and maybe to fix.

So I think it may be hard to achieve your intended goal.

That said, what you need is a very tiny bit of procrastinate, maybe the easiest way would be to implement your own pg lock. That could be a table with a single row that you would SELECT FOR UPDATE or maybe taking lock on the whole table. Or use advisory locks.

All in all, this could maybe be much less code than implementing procrastinate for this issue given all the things you'll have to undo in procrastinate, and it would be easier to understand for pther people or you in 6 months.

Good luck !

**Comment by matthewcummings** [comment]
First of all, thank you for the follow up and complete response. Yes, my use case is the latter, I want to call a locking mechanism in my Flask startup script in each container.

Given what you've just said, I agree, `procrastinate` doesn't feel like a perfect fit for my use case.

**Comment by ewjoachim** [comment]
Thanks for your kind words :)
