### ISSUE TITLE
`add_tasks_from` modifying the application?

### ISSUE THREAD

**Issue by mecampbellsoup** [procrastinate-org/procrastinate#586]
Hi @ewjoachim,

In our test environment, we use `pytest` and are trying to monkeypatch our async procrastinate application as follows:

```python
@pytest.fixture
async def patch_async_app(monkeypatch: pytest.MonkeyPatch):
    original_app = main.procrastinate_app
    with monkeypatch.context() as mp:
        in_memory_async_app = App(connector=InMemoryConnector())
        in_memory_async_app.add_tasks_from(original_app, namespace="original")
        mp.setattr(main, "procrastinate_app", in_memory_async_app)
        yield in_memory_async_app
        in_memory_async_app.connector.reset()
```
The first test that uses this fixture passes just fine with these log entries:

```
[cloud-app] INFO:procrastinate.jobs:job_defer app.gql_mutations.defer_create_namespace_in_k8s[5]({'namespace': 'tenant-test-org1-b78d-test'})
[cloud-app-worker-k8s] INFO:procrastinate.worker.k8s-worker:start_job app.gql_mutations.defer_create_namespace_in_k8s[5]({'namespace': 'tenant-test-org1-b78d-test'})
```
(Note that we only recently started using the `InMemoryConnector` in tests so we have some fixtures/test code that relies on actually enqueuing a task that is then picked up by a procrastinate worker, so in effect we have _both_ in-memory and the "normal" task pipelines when we run these tests.)

However, the next test (using the exact same fixtures) then fails with the following logs:

```
[cloud-app] INFO:procrastinate.jobs:job_defer original:app.gql_mutations.defer_create_namespace_in_k8s[3]({'namespace': 'tenant-test-org2-c40f-test'})
```

Interestingly/strangely, the app name is now _namespaced_ `original:app`, which I can only assume is coming from our `add_tasks_from` usage above since we pass `namespace="original"` there and only there.

Is it possible that `add_tasks_from` is doing some kind of mutation of the `app` object, or am I just doing something stupid that I can't yet see?

Thanks for your time! 😅

**Comment by ewjoachim** [comment]
Hey @mecampbellsoup ! Thanks for taking the time to make a detailed ticket !

I could be wrong, but I believe rather than `add_tasks_from` which is a method that's been introduced for blueprints (so making re-usable groups of tasks), what you're looking for is [`with_connector`](https://procrastinate.readthedocs.io/en/stable/reference.html#procrastinate.App.with_connector) which I think is closer from what you're trying to do.

Let me know if changing this is enough for your usecase. Also, if it works, and if you have opinions on what should be changed in the docs to make this more obvious for the next people, please either point it or do a PR :)

**Comment by mecampbellsoup** [comment]
Thanks for such a prompt response @ewjoachim! 🙏 

This definitely is a better fit for our use-case! This is probably outside of the scope of this ticket/issue (as I'm fairly sure my issue is related to mocking/patching patterns and not procrastinate per se) but - the issue I'm facing now is that our `@task_with_database` method, which enqueues tasks using our `async_app` procrastinate app (the thing I'm trying to patch above), seems to _not_ be using the patched application generated from using `with_connector` and monkeypatching.

```python
# app/procrastinate.py

async_app = App(
    connector=async_app_connector,
    import_paths=PROCRASTINATE_IMPORT_PATHS,
)

# most file content omitted...

database_lock = asyncio.Lock()


def task_with_database(*args, **kwargs):
    def wrap(coro):
        @wraps(coro)
        async def new_coro(*job_args, **job_kwargs):
            if not database.is_connected:
                async with database_lock:
                    # while waiting for the lock, another job may have
                    # connected the database already
                    if not database.is_connected:
                        print("Connecting to the database...")
                        await database.connect()
            return await coro(*job_args, **job_kwargs)

        print(
            "async_app in task_with_database",
            type(async_app),
            type(async_app.connector),
        )
        return async_app.task(*args, **kwargs)(new_coro)

    return wrap
```

I think this is happening because the decorator continues to use the non-patched `async_app` application since the `async_app` that it references is defined directly above that function definition in this same file, so when our FastAPI application is loaded at the beginning of test runs the patch hasn't been defined/activated yet.

If you have any thoughts/suggestions I'd love to hear them otherwise I think we can close this issue.

P.S. do you have any idea _why_ in my first comment the subsequent tests showed the app as being namespaced `original:` like that?!

**Comment by ewjoachim** [comment]
> P.S. do you have any idea why in my first comment the subsequent tests showed the app as being namespaced original: like that?!

Yes. The intended purpose of [blueprints](https://procrastinate.readthedocs.io/en/stable/howto/blueprints.html) though I should definitely make documentation much clearer about that.

The idea is that a lib that exposes procrastinate tasks would do so by defining a Blueprint and then defining tasks on that blueprint:
```python
@blueprint.task
def mytask(...):
    ...
```

As the app owner using this lib, you would want to import those tasks to your app with `app.add_tasks_from(blueprint)`, but in order to avoid namespace collision, when doing this you have to provide a namespace, and the tasks are registered as having this namespace prefixed through their names. I'd love to avoid mutating tasks when we load them in the app, but the API allowing to do task.defer without specifying the app means the task needs to somehow keep track of its full name.

That say maybe we'll find something clever someday to make this better.

**Comment by ewjoachim** [comment]
> P.P.S I think my best approach here will be to rewrite our test suite to always and exclusively use the InMemoryConnector.

Yes I think so too, at least for the time being.

Well one less monkeypatch in the world, I can't say I hate that but I understand it would be easier to take the shortcut.

I think there's something annoying in the fact that there are so many references to the app everywhere so when you want to patch it it's so hard. I'm not sure what the clean refactor route would be, I think we need to think think this through with anyone interested :)

**Comment by mecampbellsoup** [comment]
For posterity, I ended up just manually updating the task whose behavior I'm testing to set its app blueprint to my patched procrasinate application (the one that uses `InMemoryConnector`):

```python
@pytest.fixture
async def patch_async_app(monkeypatch: pytest.MonkeyPatch):
    original_app = main.procrastinate_app
    with monkeypatch.context() as mp:
        in_memory_async_app = original_app.with_connector(connector=InMemoryConnector())
        send_risk_score_event_task: Task = in_memory_async_app.tasks.get(
            "app.sift.send_risk_score_event"
        )
        send_risk_score_event_task.blueprint = in_memory_async_app
        mp.setattr(main, "procrastinate_app", in_memory_async_app)
        yield in_memory_async_app
        in_memory_async_app.connector.reset()
```
As a result, this task runs "in memory" (does not get performed by some separate worker process like we do in production) and my tests can assert on the side effects/results of `send_risk_score_event`.

**Comment by ewjoachim** [comment]
```
send_risk_score_event_task.blueprint = in_memory_async_app
```
You may want to undo that after the yield, otherwise you'll end up keeping a reference to the in memory app forever in your tests.

**Comment by ewjoachim** [comment]
Yep
