### ISSUE TITLE
clarify docs for schedule_in param of configure()

### ISSUE THREAD

**Issue by abe-winter** [procrastinate-org/procrastinate#592]
Hi! great library.

The `schedule_in` docs say 'a dict describing a time interval', here:
https://github.com/procrastinate-org/procrastinate/blob/781cbdf0ce272f9bc449acbccc8caa65108c6649/procrastinate/tasks.py#L162

Might be clearer to say explicitly these are kwargs for a timedelta? I had to dig in code to figure this out:
https://github.com/procrastinate-org/procrastinate/blob/781cbdf0ce272f9bc449acbccc8caa65108c6649/procrastinate/tasks.py#L28

thanks again for publishing this

**Comment by ewjoachim** [comment]
You're definitely right !

Are you interested to contribute this ?

**Comment by abe-winter** [comment]
sure! I'll submit a PR in the next few days
