### ISSUE TITLE
Improve documentation on "Monitor Procrastinate in a real environment"

### ISSUE THREAD

**Issue by kbakk** [procrastinate-org/procrastinate#606]
Hi,

We are running a small scale procrastinate setup in our production environment.

The [Monitor Procrastinate in a real environment](https://procrastinate.readthedocs.io/en/stable/howto/monitoring.html) ([rst permalink](https://github.com/procrastinate-org/procrastinate/blob/4dd9da0acf32fb351f3ee0ab5ca8083b54df82c1/docs/howto/monitoring.rst)) documentation is something I believe should be expanded upon.

**Comment by kbakk** [comment]
Our strategy is currently to check that there's no stalled/non-completed jobs, using this query:

```sql
select coalesce(sum(age(current_timestamp, pe.at)), interval '0 seconds') as total_jobs_age,
       count(pj.id)                                                       as job_count
from procrastinate_jobs as pj
  left join procrastinate_events as pe on pj.id = pe.job_id
where pj.status not in ('succeeded', 'failed')
  and pe.type = 'deferred'
  and pj.id not in (
    -- get a list of all jobs scheduled sometime in the future
    -- e.g. jobs that have been scheduled to run at a later date
    -- or been scheduled for retry
    select pj.id
    from procrastinate_jobs as pj
      left join procrastinate_events as pe on pj.id = pe.job_id
    where pj.status not in ('succeeded', 'failed')
      and pe.type = 'scheduled'
      and pe.at > current_timestamp
    order by pe.at
```

We have written a Prometheus exporter to expose this, and are then presenting the two values (total_jobs_age, job_count) in a Grafana dashboard with alerts on thresholds. 

In addition are we running Sentry, which catches exceptions thrown (nothing special, just `sentry_sdk.init(dsn=sentry_dsn, environment=env)`).

Curious to hear if there are issues with this approach. Also if there are "blind spots" we should consider.

**Comment by abe-winter** [comment]
@kbakk is sentry catching exceptions without additional setup? I wrote a decorator to get it working, but I didn't think to test if errors are captured with just a call to `init()`

**Comment by ewjoachim** [comment]
Hey ! I somehow completely missed the notification for the original issue, sorry :/

You're right, there are a lot of things we can do to improve both the processes and the documentation. Would you be interested in contributing in this direction ?

**Comment by abe-winter** [comment]
this is the decorator I use for sentry capture:

```python3
def pro_wrap(*args, **kwargs):
    "decorator to register queue task + send errors to sentry. takes same arguments as procrastinate app task() decorator. wrapped function must be async"
    queue_name = kwargs.get('queue', '?')
    def inner_decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except:
                sentry_sdk.capture_exception(tags={'queue': queue_name, 'task': func.__name__})
                raise
        return pro.task(*args, **kwargs)(wrapper)
    return inner_decorator

@pro_wrap(queue='test')
async def crash_task():
    raise IntentionalError
```

re submitting a PR -- from a design perspective, seems cleaner to offer a generic hook for error capture, rather than supporting sentry_sdk specifically?

it looks like the worker call stack is (`single_worker` -> `process_job` -> `run_job`), with error capture happening in run_job here:

https://github.com/procrastinate-org/procrastinate/blob/781cbdf0ce272f9bc449acbccc8caa65108c6649/procrastinate/worker.py#L239

would you be interested in a PR that adds an `error_handler` argument to the `App` class, and then calls that in the `except` block in L239 above?

(also, it sounds like kbakk is getting this done without fancy extra wrapping? my solution may be overkill)

**Comment by ewjoachim** [comment]
I'm going to ask a silly question, but given that we already call `logger.error(exc_info=True)`, doesn't the [Sentry logging integration](https://docs.sentry.io/platforms/python/guides/logging/) already do the same ?

**Comment by abe-winter** [comment]
ohhh you're right

I wasn't seeing this before because in my testing setup, the worker doesn't stay up long enough for sentry to report errors. When I leave it up, the sentry logging integration does the trick

yes

**Comment by ewjoachim** [comment]
That said... It's probably worth it mentioning this in the docs.

**Comment by abe-winter** [comment]
I'm happy to submit a docs-only PR that adds a 'sentry' section to the 'monitoring' page. Interested?

**Comment by ewjoachim** [comment]
Absolutely :)
