### ISSUE TITLE
Missing `typing_extensions` from dependencies

### ISSUE THREAD

**Issue by mariaemancipium** [procrastinate-org/procrastinate#644]
Hey - new here so forgive me if I'm missing something obvious.

I was testing Procrastinate for use on a project, and I ran into a dependency that might need to be added to your pyproject.toml. I haven't used Poetry before so don't know how that works exactly... I've only ever used requirements.txt.

I'm running python 3.9. I got a dependency error when I tried running the package. It said I needed to install **typing_extensions**.

Maybe that's just a basic package that should already be installed by default, idk - but if not, there you go, a quick add to your list so users can install more quickly.

**Comment by ewjoachim** [comment]
You're right. This dependency may or may not be installed as a sub-dependency from other dependencies, and it's possible that it's a subdependency of our developer dependencies, which is most probably why we didn't catch it before.

There are 3 steps to the fix we need to do:
- Search in the code where we use it. I believe it's here:
https://github.com/procrastinate-org/procrastinate/blob/781cbdf0ce272f9bc449acbccc8caa65108c6649/procrastinate/cli.py#L10

So the reason we're loading something from typing_extensions is to get [`Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) which is "New in version 3.8"

- Change this code: use `Literal` from `typing` instead (`typing` is in the standard library):
```python
import sys

if sys.version < (3, 8):
    from typing_extensions import Literal
else:
    from typing import Literal
```
(There are multiple ways of handling conditional imports, but the explicit check on sys.version lets the code be very explicit for at what point we can remove the branch. I even believe pyupgrade will be able to remove the branch one day, when we tell it to only support 3.8+)

- Declare the dependency in `pyproject.toml`, with a marker to be installed only for older python versions:
```toml
[tool.poetry.dependencies]
(...)
typing-extensions = {version = "*", python = "<3.8"}
```
And then re-run `poetry update` and commit the result (note: see the contributing doc for installing tools such as poetry).

Would you be interested in submitting the PR yourself ?

**Comment by mariaemancipium** [comment]
Absolutely. It might take a sec for me to get up to speed w/ poetry etc but I'd love to chip in.

I'll review the contributing doc, I'm guessing everything I need to be aware of for contributing should be in there?

BTW - it's looking likely I'll be leaning on this code for a project I'm building for a client. I know its still pre v 1.0 but its better than what I've used so far. As things come up I'll do my best to help solve where I can.

**Comment by ewjoachim** [comment]
Great ;)

In my side, I'll be super explicit: I'm doing the best I can to help the project, but I'm not anymore in a situation where I use procrastinate myself, so it's slightly harder to invest a lot of time on it. I'll try to support people willing to contribute :)

**Comment by mariaemancipium** [comment]
@ewjoachim makes sense - hopefully I can find some more ways to contribute. I've noticed another issue or two as I've begun testing, I'll write them up when I understand them more and I have time.

**Comment by mariaemancipium** [comment]
Do I need to be given write access to this repo? Cloned it, made the changes, committed them to a new branch locally, and went to push it but it said I didn't have access and I could try forking instead. Is there a way to open a PR from a fork, or do I just need to be given write access?

**Comment by ewjoachim** [comment]
No problem :)

Yes, typically, when contributing to a project you don't own on GitHub, you fork it and define 2 "remotes" on your local setup. What you typically end up with is a remote named "origin" which point to your fork, and a remote named "upstream" which points to the repo.

Currently, chances are that your "origin" remote is the main repo, so you're going to want to use `git remote rename origin upstream`.

Then, `git remote add origin <git url of your fork>`.

Then you'll push to origin, when doing so, git will show you an URL for opening a PR, and by defaut, this PR will be from your branch on your fork to the main branch on the upstream repo.

I'm conscious that my directions may seem a bit dry, and knowing exactly what to do may need some time and/or knowledge of your specific setup.

I'm pretty sure there are solid learning resources on how to use Git and GitHub together in the scope of open source contributions, though I can't really point to one in particular for which I'd vouch. Maybe starting from [here](https://docs.github.com/en/get-started/quickstart/git-and-github-learning-resources) would make sense, though I'm not sure it covers the points you need exactly. That said, youtube seems to offer multiple crash courses to contributing to an open source repo on GitHub.
