### ISSUE TITLE
functools.partial not compatible with App.task decorator

### ISSUE THREAD

**Issue by abe-winter** [procrastinate-org/procrastinate#674]
## Issue

Functions that have been curried with python's built-in [functools.partial](https://docs.python.org/3.10/library/functools.html?highlight=functools#functools.partial) will crash inside the `App.task` decorator, because partial instances don't have a `__name__`.

Easy to work around (see below), so not urgent.

## Workaround

Setting `name` in the task config seems to solve this.

```diff
- my_task = pro.task()(functools.partial(decorated_fn, arg))
+ my_task = pro.task(name='module.task')(functools.partial(decorated_fn, arg))
```

## Possible solution

The error is happening in [get_full_path](https://github.com/procrastinate-org/procrastinate/blob/1a54ab3fedb8a421c93dc63b99aa567602801b86/procrastinate/utils.py#L237).

In theory you could detect a `partial` in there + use `obj.func.__name__` in place of `obj.__name__`. This risks `TaskAlreadyRegistered` if the same function is partialed twice in a module, but at least solves the 'first partial' case.

Sub-ideal options:
- serial suffix `f"{module}.{obj.func.__name__}-partial-{serial_index}"`. I think this is robust against import order changing, but could be broken in edge cases or if tasks are defined by functions which are called dynamically. Would also require keeping a counter somewhere
- use hash of partial arguments as suffix, but this isn't consistent across runs. (in my use case, where the partial argument is a class, hashes aren't consistent across runs)

I'm not sure how automatic task import works in the procrastinate worker, so I'm not sure if one of these breaks auto-import.

Happy to be assigned this PR if helpful + small in scope.

## Traceback

```python
File "backend/util.py", line 46, in <module>
  send_push = pro.task(queue='push')(functools.partial(push.send_push, PushToken))
File ".direnv/python-3.10.4/lib/python3.10/site-packages/procrastinate/blueprints.py", line 241, in _wrap
  task = tasks.Task(
File ".direnv/python-3.10.4/lib/python3.10/site-packages/procrastinate/tasks.py", line 93, in __init__
  self.name: str = name if name else self.full_path
File ".direnv/python-3.10.4/lib/python3.10/site-packages/procrastinate/tasks.py", line 113, in full_path
  return utils.get_full_path(self.func)
File ".direnv/python-3.10.4/lib/python3.10/site-packages/procrastinate/utils.py", line 239, in get_full_path
  return f"{_get_module_name(obj)}.{obj.__name__}"
AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Comment by ewjoachim** [comment]
My gut feeling would be that if auto-generating a name for partial function makes them a lot more brittle, maybe we should mandate providing a name whenever one consistent name cannot be extracted ? So the fix would rather be to improve the error and make it explicit that it's the developer's task to register they "partial"-based task with a name ?

**Comment by abe-winter** [comment]
I think you're right about the brittleness of automatically solving it. 'clearer error' sounds like a good fix to me

One other possible automatic naming trick: a short hash of pickle of the partial args will be consistent across restarts

But this is a lot of plumbing for an edge case, I think you're right that the right thing here is error with nudge.

**Comment by ewjoachim** [comment]
Would you be up for making a PR ?

**Comment by abe-winter** [comment]
yes sure. rough outline:
- new error for missing name
- add a test

anything else?

**Comment by ewjoachim** [comment]
I think it should be enough.
