### ISSUE TITLE
Running procrastinate in fastapi hangs with SIGINIT

### ISSUE THREAD

**Issue by sevaho** [procrastinate-org/procrastinate#687]
Hi

When running procrastinate in fastapi and doing a SIGINT, the application hangs.

```python
from fastapi import FastAPI
import asyncio
from procrastinate import App, AiopgConnector

app = FastAPI()

task_queue = App(connector=AiopgConnector(dsn="postgresql://postgres:docker@localhost:11001"))


@app.on_event("startup")
async def setup() -> None:
    print("STARTUP")

    await task_queue.open_async()
    asyncio.create_task(task_queue.run_worker_async())


@app.on_event("shutdown")
async def teardown() -> None:
    print("SHUTDOWN")
    await task_queue.close_async()


@app.get("/")
async def root():
    return {"Hello": "World"}
```

When executing `CTRL-C` I see the following output:

```
INFO:     Started server process [812800]
INFO:     Waiting for application startup.
STARTUP
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
^C^C^C^C^C
```

The fastapi application is stuck.

Any ideas how to mitigate/fix?

**Comment by ewjoachim** [comment]
I don't have a specific idea, but if you investigate and find something, let us know :)

**Comment by sevaho** [comment]
Ok no problem.

I will investigate.

This is indeed hacky, but I think the combo of a http framework + power to act as a worker is very powerful.

Thanks for this awesome library btw!

**Comment by sevaho** [comment]
Hello @ewjoachim,

Just tested, and it doesn't hang anymore!
Thanks for the fix!
