### ISSUE TITLE
Feature request: enable retries by default for all jobs

### ISSUE THREAD

**Issue by adibsaad** [procrastinate-org/procrastinate#737]
As per this doc https://procrastinate.readthedocs.io/en/stable/howto/retry.html

We have to specify a retry strategy for every task we create. Would it be possible to add a `retry` option to the procrastinate `App` class so that all tasks are retried by default?

**Comment by ewjoachim** [comment]
maybe the easiest way would be to use you own decorator for building tasks, which would have your default value for `retry` ?

[functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) is likely to help in that.

**Comment by ewjoachim** [comment]
```python
app = ...

my_task = functools.partial(app.task, retry=True)

@mytask
def some_task():
	...
```
(of course, using a better name than `my_task` is advised)
