### ISSUE TITLE
How to extend the applied schema

### ISSUE THREAD

**Issue by bmarsh9** [procrastinate-org/procrastinate#746]
Is there a supported way for extending the schema that is applied when running `procrastinate --app=app.utils.bg_worker.bg_app schema --apply`?

I am trying to add an additional column (`created_at`) to the `procrastinate_jobs` table so that it is automatically populated when Im querying the API (`app.list_jobs()`)

```
CREATE TABLE procrastinate_jobs (
    id bigserial PRIMARY KEY,
    queue_name character varying(128) NOT NULL,
    task_name character varying(128) NOT NULL,
    lock text,
    queueing_lock text,
    args jsonb DEFAULT '{}' NOT NULL,
    status procrastinate_job_status DEFAULT 'todo'::procrastinate_job_status NOT NULL,
    scheduled_at timestamp with time zone NULL,
    created_at timestamp with time zone DEFAULT NOW() NULL, # NEW
    attempts integer DEFAULT 0 NOT NULL
);
```

Thanks!

**Comment by bmarsh9** [comment]
I'm looking at https://procrastinate.readthedocs.io/en/stable/howto/migrations.html#migrate-the-procrastinate-schema as a possible way but wondering if you can apply the schema and not have to perform a migration

**Comment by ewjoachim** [comment]
Have you seen the table `procrastinate_events` ? It has `job_id`s, `type` (you're looking for "deferred") and `at` which is a timestamp. I believe it's the info you're looking for.

**Comment by bmarsh9** [comment]
Yeah I see that table. Ok that will be fine.. Thanks!
