### ISSUE TITLE
Fix the sync/async compatibilty

### ISSUE THREAD

**Issue by ewjoachim** [procrastinate-org/procrastinate#751]
I think procrastinate is very very bad at handling sync/async compatibility.

I'm pretty sure now that the way to go is to use [`loop.run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) probalby with a call to `set_default_executor` in the `App` (and a new optional `App` constructor argument).

That said, I know that a great deal of work has been set to make this safer in [asgiref](https://github.com/django/asgiref/blob/main/asgiref/sync.py) with `sync_to_async` and  `async_to_sync`. I'd say we'd need to:

- read the code of these functions, understand what it does and the risk we take by not using them
- weight on
- reimplement our compatibility layer using either solution
- test, abundantly

I don't know if I'll have the time to dedicate to that, especially if I'm alone, but I'll gladly mentor anyone interested.

**Comment by ewjoachim** [comment]
I've started working on a PR using asgiref, and the plan is to add a Django test that uses the ORM in a task, and a test that defers a task (mixing sync and async code).

For now, it's not far from working but the django test's teardown fails because when it tries to delete the DB, "someone else" is using it. I'll need to spend some time on this (if anyone is inspired, feel free to have a go.)

**Comment by turicas** [comment]
Awesome! What do you think in running the worker in another process controlled by the test case and killing this process on tear down?
