### ISSUE TITLE
SqlAlchemy sync  fails

### ISSUE THREAD

**Issue by fexd12** [procrastinate-org/procrastinate#771]
I'm getting this error, using SlqAlchemy.

 A synchronous connector (probably Psycopg2Connector) was used, but the operation
    needs an asynchronous connector (AiopgConnector). Please check your App
    configuration.
    

The above exception was the direct cause of the following exception:

my code:

```python
from procrastinate import AiopgConnector, App, JobContext, Psycopg2Connector
from procrastinate.contrib.sqlalchemy import SQLAlchemyPsycopg2Connector

dsn = 'postgresql://{}:{}@{}:{}/{}'.format(
    user, password, host, port, database
)

engine = create_engine(dsn,
                       connect_args={'options': '-csearch_path={}'.format(schema)},
                       echo=True)

app = App(
    connector=SQLAlchemyPsycopg2Connector(),
)

@app.task(name='sum', queue='sum', pass_context=True, retry=True)
def sum(context: JobContext, a, b):
    # await asyncio.sleep(3)
    print('chamando task sum')

app.open(engine)
sum.defer(a=1, b=2)
app.run_worker()

```

any advice?

**Comment by ewjoachim** [comment]
Yep, maybe it's not stated explicitly in the docs but: https://procrastinate.readthedocs.io/en/stable/howto/sync_defer.html

You can use any connector for deferring tasks, but for launching the worker, you need to use the AiopgConnector (potentially creating 2 app objects through `with_connector`)

**Comment by fexd12** [comment]
thanks, i'll close the issue.
