### ISSUE TITLE
Enable the tasks in blueprints.py to handle Pyright's strict mode

### ISSUE THREAD

**Issue by paulzakin** [procrastinate-org/procrastinate#786]
Currently, if you do something like this: Pyright on strict mode will complain that "Type of "task" is partially unknown"

By changing the type of Callable to Callable[.... Any] it acknowledges that the decorated function can take any number of arguments and return any value. Which seems like the sort of vague typing you would want for a decorator! 

@app.task(name="my_cool_task")
def check_periodic(timestamp: int) -> None:
    logger.info("Procrastinate is running periodically!")

I opened a PR as well: https://github.com/procrastinate-org/procrastinate/pull/787

**Comment by paulzakin** [comment]
Also, question for you about blueprints in general. 

If you have four blueprints, each with three tasks, and then consolidate all twelve tasks into one blueprint, will that impact anything? Like:

- Are blueprints more cosmetic collections or tasks that are registered by the worker
- Or some form of deeper magic that are included with the task when it is registered. 

As always, love the library!

**Comment by ewjoachim** [comment]
Blueprints were created to decouple the place where tasks are defined from the place where they're registered, making it possible to define tasks in libs that you can register in your project. It solves the chicken and egg problem that existed before: tasks needed to be registered with an app, tasks lived in libraries that didn't know about your project, app was defined in your project.

Now in terms of magic, there's one annoying thing that I haven't been able to solve yet (well, I haven't spent much time working on procrastinate these days): tasks know their name, and when registering a blueprint, you specify a namespace, but for now, when you register the blueprint, the tasks are updated with their new name so if you were to register the same task twice, its name would get the namespace twice.

Ideally, tasks wouldn't be modified when registering their namespace. I think we should use a proxy object somewhere, that would hold the task and the name prefix...

Other than that, I don't think there's much magic, but I'm not sure either that I understood 100% of your question :)____

**Comment by paulzakin** [comment]
No that helps! I may just have to experiment as bit with it :)
