### ISSUE TITLE
How to catch exceptions that occur within tasks

### ISSUE THREAD

**Issue by bmarsh9** [procrastinate-org/procrastinate#795]
I'm wondering if there is a way to catch specific exceptions thrown within my tasks at a higher level (e.g. not at the task level)

```
import_paths = ["app.integrations.base.tasks"]

bg_app = procrastinate.App(
    connector=connector_class(
        host=os.environ.get("POSTGRES_HOST"),
        user=os.environ.get("POSTGRES_USER"),
        password=os.environ.get("POSTGRES_PASSWORD")
    ),
    import_paths=import_paths)
```

`app.integrations.base.tasks`

```
@bg_app.periodic(cron="* * * * *")
@bg_app.task(name="scheduler", queue="scheduler")
async def scheduler(timestamp: int):
    # the command below throws an exception, I'd like to be able to catch this error at a higher level
    # rather than doing a try/except for every single task
    Task.query.all()
```

Ideally I'd like to do the following

```
import_paths = ["app.integrations.base.tasks"]

try:
    bg_app = procrastinate.App(
        connector=connector_class(
            host=os.environ.get("POSTGRES_HOST"),
            user=os.environ.get("POSTGRES_USER"),
            password=os.environ.get("POSTGRES_PASSWORD")
        ),
        import_paths=import_paths)
except MyException as e:
    print(e)
```

Thank you for any assistance!

**Comment by bmarsh9** [comment]
This resource (https://procrastinate.readthedocs.io/en/stable/howto/retry.html) may work but I'd have to attach the exception to every task... maybe I should do that and then I can re-run the task.

**Comment by ewjoachim** [comment]
Have you seen this: https://procrastinate.readthedocs.io/en/stable/howto/middleware.html ?
It feels like it answers your question, can you confirm ?

If you want, feel free to suggest a docs improvement PR if you feel that, with different wording, you may have been able to find the page.

**Comment by bmarsh9** [comment]
@ewjoachim I remember those docs... thank you. That should work. Apologies (and the docs are good, I just missed it)
