### ISSUE TITLE
Feature request: add docs to on how to implement just-in-time computation of credentials

### ISSUE THREAD

**Issue by moretea** [procrastinate-org/procrastinate#838]
I am using procrastinate in a Django app, that will be deployed on AWS backed by an RDS PostgreSQL database. I would prefer to enable automatic password rotation, as an additional layer of security.

This partially works; for the synchronous Django code, I have been able to subclass the ThreadedConnectionPool and override [_connect](https://github.com/psycopg/psycopg2/blob/999d7a6d01a1763030ef92a9b77731238f0b0135/lib/pool.py#L61-L69), create a pool myself, and passing that to the `app.open()` method.

Unfortunately, no such easy thing is possible in `aiopg`, so I have opened https://github.com/aio-libs/aiopg/issues/903.

If this gets fxied in `aiopg`, would this project be open to a PR on how to implement this in the docs?

**EDIT:** Actually, we can do better in psycopg2 too. I've opened https://github.com/psycopg/psycopg2/issues/1625 for that purpose.

**Comment by ewjoachim** [comment]
Psycopg3 is now available, and I think it allows doing that :) Feel free to repoen if not.
