### ISSUE TITLE
[Question/Feature Request] Integrate workers w/ error logging service like Sentry

### ISSUE THREAD

**Issue by mecampbellsoup** [procrastinate-org/procrastinate#844]
Hey guys,

We recently had an issue where our procrastinate worker process was encountering an exception in _our own code_, but confusingly despite initializing our Sentry SDK we weren't getting events which made debugging more difficult.

Is there an established pattern for integrating our worker processes w/ the Sentry SDK?

**Comment by ewjoachim** [comment]
Hm, the documentation we have on that is https://procrastinate.readthedocs.io/en/stable/howto/monitoring.html#error-reporting and it came from https://github.com/procrastinate-org/procrastinate/pull/647 . So you have the same configuration, but it doesn't trigger Sentry events ?

What Procrastinate does is that when a task ends with an exception, we `logger.exception()` it. If sentry has been set up, including with logging, that should be enough. The question you want to ask is "how is logging set up in your app". For example, if it's a Django App, then I believe Django takes care of the logs setup when `django.setup()` is called, which can either be done manually, or automatically if you're launching your process through a Django entrypoint (e.g. a management command).

Does this answer your question ?

**Comment by ewjoachim** [comment]
(Closing for lack of response. Feel free to repopen if relevant)
