### ISSUE TITLE
`Worker.run_job()` not resiliant to asyncio cancellation

### ISSUE THREAD

**Issue by ashleyheath** [procrastinate-org/procrastinate#871]
Currently, if a job fails with an error that extends `BaseException` but not `Exception`, the worker will find itself in an invalid state and crash (specifically, the `log_action` variable will not be set when trying to log the outcome of attempting the job).

A seemingly common situation this will arise in is when an asyncio `CancelledError` is raised. Happy to patch, just wanted to clarify what the expected behaviour _should_ be - special case for catching `CancelledError` or catch and supress all `BaseException`s?

**Comment by ewjoachim** [comment]
Hello ! Thanks for opening this.

I believe that suppressing `BaseException`s is a bad idea. I'd tend to say that when catching a BaseException (that's not an exception) we should do whatever needs to be done so that the `finally` clause is ok, and then reraise it (or maybe just initialize our variables to a sane default value before the `try` block and not add `except` clauses, your choice. I'd favor the latter, but I'll accept both.)

**Comment by ashleyheath** [comment]
Thanks for taking a look. Having poked around the code a bit more, it's actually a little unclear to me what the expected `status` of the job should be in the event that a non-`Exception` gets raised - even if we re-raised the error from `run_job()` (after fixing the logging) it'll bubble up to `process_job()` where it'll break again.

I think my question here is whether procrastinate should attempt to schedule a retry of a job that fails with an exception extending from `BaseException` or just crash (or both)? For my use case either of supress-and-retry or retry-and-crash would work; the key thing I want to avoid is the job status not getting updated.

**Comment by ewjoachim** [comment]
Retry/Finish and crash is the most expected behaviour, I believe.

If something issued a `BaseException` that isn't an `Exception`, it's a last resort issue that should not go unnoticed.

```

**Comment by ashleyheath** [comment]
@ewjoachim, PR raised - let me know what you think when you have a moment. Cheers!

**Comment by ewjoachim** [comment]
https://github.com/procrastinate-org/procrastinate/releases/tag/0.32.0

**Comment by ashleyheath** [comment]
Much appreciated; cheers!

**Comment by ewjoachim** [comment]
Thanks for your patience ! Always happy to welcome new contributors :)

(BTW, if you have feedback on the contribution process, or consider to spend some time helping the project later, feel free :) )
