### ISSUE TITLE
Store worker name in log table

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [procrastinate-org/procrastinate#899]
There have been a few times when troubleshooting tasks that I've liked to know what worker is or was running a task. Is it possible to add the hostname + worker PID to the logs table when a task is started to help follow this up?

**Comment by ewjoachim** [comment]
I thinks it might make more sense to have this in the `procrastinate_events` table than in the jobs table. Also, workers can be given names, and I'd rather use the names than the hostname/pid which might be very random in some case (though it should be trivial to use the hostname + pid for the name of the worker, so the info can be there, but if something makes more sense to a user than hostname or PID, then they can choose).

Lastly, the worker name is already present on all the logs produced by the worker module. I wonder if this level of monitoring is something we want in the DB, or something that should be done by analyzing the project logs?

Is there a specific reason why logs weren't a working tool for your usecase?

**Comment by ewjoachim** [comment]
I'm not 100% convinced of this issue, if you don't advocate for it, I think it might be worth setting it aside for now. Feel free to reopen if relevant.
