### ISSUE TITLE
Deprecation warning for Python 3.12

### ISSUE THREAD

**Issue by paulzakin** [procrastinate-org/procrastinate#979]
Just noticed this when running Pytest - not a big deal!

==================================== warnings summary =====================================
.venv/lib/python3.12/site-packages/procrastinate/metadata.py:12
.../python3.12/site-packages/procrastinate/metadata.py:12: DeprecationWarning: Implicit None on return values is deprecated and will raise KeyErrors.
    "email": metadata["Author-email"],
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

**Comment by ewjoachim** [comment]
nice to know. I'll try to fix it.
