### ISSUE TITLE
Errors with v2

### ISSUE THREAD

**Issue by paulzakin** [procrastinate-org/procrastinate#981]
The first one is new on v2. We deployed v2 to production last night. Overall, it seems to be working! However, two errors are emerging. 

The first one:
```sql
Main coroutine error, initiating remaining coroutines stop. Cause: IntegrityError('duplicate key value violates unique constraint "procrastinate_jobs_queueing_lock_idx"\nDETAIL: Key (queueing_lock)=(recurring_notifications_sender) already exists.\nCONTEXT: SQL statement "INSERT INTO procrastinate_jobs (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n VALUES (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n RETURNING id"\nPL/pgSQL function procrastinate_defer_job(character varying,character varying,text,text,jsonb,timestamp with time zone) line 5 at SQL statement\nSQL statement "UPDATE procrastinate_periodic_defers\n SET job_id = procrastinate_defer_job(\n _queue_name,\n _task_name,\n _lock,\n _queueing_lock,\n _args,\n NULL\n )\n WHERE id = _defer_id\n RETURNING job_id"\nPL/pgSQL function procrastinate_defer_periodic_job(character varying,charac...
```

The second one:
```sql
periodic_deferrer error: IntegrityError('duplicate key value violates unique constraint "procrastinate_jobs_queueing_lock_idx"\nDETAIL: Key (queueing_lock)=(recurring_notifications_sender) already exists.\nCONTEXT: SQL statement "INSERT INTO procrastinate_jobs (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n VALUES (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n RETURNING id"\nPL/pgSQL function procrastinate_defer_job(character varying,character varying,text,text,jsonb,timestamp with time zone) line 5 at SQL statement\nSQL statement "UPDATE procrastinate_periodic_defers\n SET job_id = procrastinate_defer_job(\n _queue_name,\n _task_name,\n _lock,\n _queueing_lock,\n _args,\n NULL\n )\n WHERE id = _defer_id\n RETURNING job_id"\nPL/pgSQL function procrastinate_defer_periodic_job(character varying,character varying,character varying,character va...
```

The latter one is maybe tied to this?

```
{
action: stopping_worker,
duration: 0.708897590637207,
end_timestamp: 1710256564.7602303,
result: null,
start_timestamp: 1710256564.051333,

worker: {
id: null,
name: worker,
queues: null
}
}
```

Happy to provide any more context, as needed. Frankly, I'm not even sure they are really "errors", in which case I need to exclude them from Sentry I'd imagine.

**Comment by paulzakin** [comment]
Ok, after a couple of days - the errors are not going away, so not a "temporary hiccup" thing. 

I'm not even sure it's an error, in that the queing lock is doing it's job? `Cause: IntegrityError('duplicate key value violates unique constraint "procrastinate_jobs_queueing_lock_id`. I feel like maybe the underlying library should just discard the error?

**Comment by ewjoachim** [comment]
Thanks for the update ! Haven't had the time to investigate, but I hear your "no pressure" statement. I'll still try to have a look at some point, though. Thank you !

**Comment by paulzakin** [comment]
Yup, no pressure at all!

**Comment by ewjoachim** [comment]
(I'm like 99.57% sure that the issue I fixed was the issue you had, but feel free to shout if it's not the case)

**Comment by paulzakin** [comment]
Awesome, I'll let you know when we deploy on Monday!

**Comment by paulzakin** [comment]
Not the case :(

These are the messages I get from Sentry

---

Main coroutine error, initiating remaining coroutines stop. Cause: IntegrityError('duplicate key value violates unique constraint "procrastinate_jobs_queueing_lock_idx"\nDETAIL: Key (queueing_lock)=(recurring_assign_addresses_to_geocode) already exists.\nCONTEXT: SQL statement "INSERT INTO procrastinate_jobs (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n VALUES (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n RETURNING id"\nPL/pgSQL function procrastinate_defer_job(character varying,character varying,text,text,jsonb,timestamp with time zone) line 5 at SQL statement\nSQL statement "UPDATE procrastinate_periodic_defers\n SET job_id = procrastinate_defer_job(\n _queue_name,\n _task_name,\n _lock,\n _queueing_lock,\n _args,\n NULL\n )\n WHERE id = _defer_id\n RETURNING job_id"\nPL/pgSQL function procrastinate_defer_periodic_job(character varying...

Main coroutine error, initiating remaining coroutines stop. Cause: IntegrityError('duplicate key value violates unique constraint "procrastinate_jobs_queueing_lock_idx"\nDETAIL: Key (queueing_lock)=(recurring_assign_addresses_to_geocode) already exists.\nCONTEXT: SQL statement "INSERT INTO procrastinate_jobs (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n VALUES (queue_name, task_name, lock, queueing_lock, args, scheduled_at)\n RETURNING id"\nPL/pgSQL function procrastinate_defer_job(character varying,character varying,text,text,jsonb,timestamp with time zone) line 5 at SQL statement\nSQL statement "UPDATE procrastinate_periodic_defers\n SET job_id = procrastinate_defer_job(\n _queue_name,\n _task_name,\n _lock,\n _queueing_lock,\n _args,\n NULL\n )\n WHERE id = _defer_id\n RETURNING job_id"\nPL/pgSQL function procrastinate_defer_periodic_job(character varying...

**Comment by paulzakin** [comment]
I'm just gonna exclude the error with Sentry - consider this one closed!
