### ISSUE TITLE
remote communication?

### ISSUE THREAD

**Issue by spxneo** [procrastinate-org/procrastinate#995]
what i want to achieve is some way to distribute jobs to workers remotely

the server delegates task

workers elsewhere from different IP receive the task and post the results back to the server

how can i make this possible? real time updates of the progress should be subscribable

**Comment by ewjoachim** [comment]
As of now, Procrastinate doesn't define a built-in way to send results. Consequently, it's the responsibility of your tasks to do that part (storing the result). Similarly for progress updates. You could use a table that you control to store results. And you could use a postgres listen/notify to actively inform your server of the progression.

See https://github.com/procrastinate-org/procrastinate/issues/370
